#!/usr/bin/env node
// Generates src/lib/version.ts at build time so the running app can
// surface its package.json version + the git SHA it was built from.
// Runs via `prebuild` so a missing/dirty git tree just falls back to
// "dev" instead of breaking the build.

import { execFileSync } from "node:child_process";
import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const version = pkg.version;

let sha = "dev";
let shaShort = "dev";
let dirty = false;
try {
  sha = execFileSync("git", ["rev-parse", "HEAD"], {
    cwd: root,
    stdio: ["ignore", "pipe", "ignore"],
  })
    .toString()
    .trim();
  shaShort = sha.slice(0, 7);
  const status = execFileSync("git", ["status", "--porcelain"], {
    cwd: root,
    stdio: ["ignore", "pipe", "ignore"],
  })
    .toString()
    .trim();
  dirty = status.length > 0;
} catch {
  // Not a git checkout (e.g. tarball install) — leave as "dev".
}

const builtAt = new Date().toISOString();

const out = `// AUTO-GENERATED by scripts/build-version.mjs — do not edit by hand.
// Regenerated on every \`npm run build\` via the prebuild hook.

export const VERSION = ${JSON.stringify(version)};
export const GIT_SHA = ${JSON.stringify(sha)};
export const GIT_SHA_SHORT = ${JSON.stringify(shaShort)};
export const GIT_DIRTY = ${JSON.stringify(dirty)};
export const BUILT_AT = ${JSON.stringify(builtAt)};

/** "v0.4.0 · 1a2b3c4" or "v0.4.0 · 1a2b3c4-dirty" */
export const VERSION_LABEL =
  "v" + VERSION + " · " + GIT_SHA_SHORT + (GIT_DIRTY ? "-dirty" : "");
`;

writeFileSync(resolve(root, "src/lib/version.ts"), out);
console.log(`[build-version] wrote src/lib/version.ts → v${version} (${shaShort}${dirty ? "-dirty" : ""})`);
